//priority: 1001
const wood_registry = [];

let wood_types = {
    // ars_elemental: ['yellow_archwood'],
    // ars_nouveau: ['blue_archwood', 'green_archwood', 'purple_archwood', 'red_archwood'],
    arts_and_crafts: ['cork'],
    evilcraft: ['undead'],
    deeperdarker: ['echo'],
    occultism: ['otherworld'],
    productivetrees: [
        'alder',
        'allspice',
        'almond',
        'apricot',
        'aquilaria',
        'asai_palm',
        'ash',
        'aspen',
        'avocado',
        'balsa',
        'balsam_fir',
        'banana',
        'beech',
        'beliy_naliv_apple',
        'black_cherry',
        'black_ember',
        'black_locust',
        'blackthorn',
        'blue_mahoe',
        'blue_yonder',
        'boxwood',
        'brazil_nut',
        'brazilwood',
        'breadfruit',
        'brown_amber',
        'buddhas_hand',
        'bull_pine',
        'butternut',
        'cacao',
        'candlenut',
        'carob',
        'cashew',
        'cave_dweller',
        'cedar',
        'cempedak',
        'ceylon_ebony',
        'cherry_plum',
        'cinnamon',
        'citron',
        'clove',
        'cocobolo',
        'coconut',
        'coffea',
        'copoazu',
        'copper_beech',
        'cork_oak',
        'cultivated_pear',
        'date_palm',
        'dogwood',
        'douglas_fir',
        'elderberry',
        'elm',
        'european_larch',
        'finger_lime',
        'firecracker',
        'flickering_sun',
        'flowering_crabapple',
        'foggy_blast',
        'ginkgo',
        'golden_delicious_apple',
        'grandidiers_baobab',
        'granny_smith_apple',
        'grapefruit',
        'great_sallow',
        'greenheart',
        'hawthorn',
        'hazel',
        'holly',
        'hornbeam',
        'ipe',
        'iroko',
        'jackfruit',
        'juniper',
        'kapok',
        'key_lime',
        'kumquat',
        'lawson_cypress',
        'lemon',
        'lime',
        'loblolly_pine',
        'logwood',
        'mahogany',
        'mandarin',
        'mango',
        'monkey_puzzle',
        'moonlight_magic_crepe_myrtle',
        'myrtle_ebony',
        'nectarine',
        'night_fuchsia',
        'nutmeg',
        'old_fustic',
        'olive',
        'orange',
        'osage_orange',
        'padauk',
        'pandanus',
        'papaya',
        'peach',
        'pecan',
        'persimmon',
        'pink_ipe',
        'pink_ivory',
        'pistachio',
        'plantain',
        'plum',
        'pomegranate',
        'pomelo',
        'prairie_crabapple',
        'purple_blackthorn',
        'purple_crepe_myrtle',
        'purple_ipe',
        'purple_spiral',
        'purpleheart',
        'rainbow_gum',
        'red_banana',
        'red_crepe_myrtle',
        'red_delicious_apple',
        'red_maple',
        'rippling_willow',
        'rose_gum',
        'rosewood',
        'rowan',
        'rubber_tree',
        'salak',
        'sand_pear',
        'sandalwood',
        'satsuma',
        'sequoia',
        'silver_fir',
        'silver_lime',
        'slimy_delight',
        'socotra_dragon',
        'soul_tree',
        'sour_cherry',
        'soursop',
        'sparkle_cherry',
        'star_anise',
        'star_fruit',
        'sugar_apple',
        'sugar_maple',
        'swamp_gum',
        'sweet_chestnut',
        'sweet_crabapple',
        'sweetgum',
        'sycamore_fig',
        'tangerine',
        'teak',
        'thunder_bolt',
        'time_traveller',
        'tuscarora_crepe_myrtle',
        'walnut',
        'water_wonder',
        'wenge',
        'western_hemlock',
        'white_ipe',
        'white_poplar',
        'white_willow',
        'whitebeam',
        'wild_cherry',
        'yellow_meranti',
        'yew',
        'zebrano'
    ]
};

Object.keys(wood_types).forEach((mod) => {
    wood_types[mod].forEach((type) => {
        if (mod == 'evilcraft') {
            wood_registry.push({
                log: `${mod}:${type}_log`,
                stripped_log: `${mod}:${type}_log_stripped`,
                wood: `${mod}:${type}_wood`,
                stripped_wood: `${mod}:${type}_wood_stripped`
            });
        } else if (mod == 'productivetrees') {
            wood_registry.push({
                log: `${mod}:${type}_log`,
                stripped_log: `${mod}:${type}_stripped_log`,
                wood: `${mod}:${type}_wood`,
                stripped_wood: `${mod}:${type}_stripped_wood`
            });
        } else if (mod == 'ars_elemental') {
            wood_registry.push({
                log: `${mod}:${type}_log`,
                stripped_log: `${mod}:stripped_${type}_log`,
                wood: `${mod}:${type}`,
                stripped_wood: `${mod}:stripped_${type}`
            });
        } else {
            wood_registry.push({
                log: `${mod}:${type}_log`,
                stripped_log: `${mod}:stripped_${type}_log`,
                wood: `${mod}:${type}_wood`,
                stripped_wood: `${mod}:stripped_${type}_wood`
            });
        }
    });
});
