RecipeViewerEvents.addInformation('item', (event) => {
    // https://kubejs.com/wiki/events/RecipeViewerEvents/addInformation
    const descriptions = [
        {
            filter: ['ae2:sky_dust'],
            text: ['Sky Dust can be generated by pointing an Annihilation Plane at the sky at build limit (§2Y=319§r).']
        },
        {
            filter: beheading_tools,
            text: ['Easily cleaves the heads from your foes!']
        },
        {
            filter: [
                'minecraft:zombie_head',
                'minecraft:creeper_head',
                'minecraft:piglin_head',
                'minecraft:dragon_head',
                'minecraft:skeleton_skull',
                'minecraft:wither_skeleton_skull'
            ],
            text: ['Heads may be obtained from mobs by killing them with particularly powerful axes and paxels.']
        }
    ];

    descriptions.forEach((description) => {
        event.add(description.filter, description.text);
    });
});
