RecipeViewerEvents.addInformation('item', (event) => {
    // https://kubejs.com/wiki/events/RecipeViewerEvents/addInformation

    /* Format Codes
    Obfuscated      §k
    Bold            §l
    Strikethrough   §m
    Underline       §n
    Italic          §o
    Reset format    §r

    Colors:
    Dark Red        §4
    Red             §c
    Gold            §6
    Yellow          §e
    Dark Green      §2
    Green           §a
    Aqua            §b
    Dark Aqua       §3
    Dark Blue       §1
    Blue            §9
    Light Purple    §d
    Dark Purple 	§5
    White           §f
    Gray            §7
    Dark Gray       §8
    Black           §0

    */
    const descriptions = [
        {
            filter: ['ae2:sky_dust'],
            text: ['Sky Dust can be generated by pointing an Annihilation Plane at the sky at build limit (§2Y=319§r).']
        },
        {
            filter: beheading_tools,
            text: ['Easily cleaves the heads from your foes!']
        },
        {
            filter: [
                'minecraft:zombie_head',
                'minecraft:creeper_head',
                'minecraft:piglin_head',
                'minecraft:dragon_head',
                'minecraft:skeleton_skull',
                'minecraft:wither_skeleton_skull',
                'enderio:enderman_head'
            ],
            text: [
                'Heads may be obtained from mobs by killing them with particularly powerful axes and paxels.',
                ' ',
                'Search for §5#beheading§r in EMI for a list!'
            ]
        },
        {
            filter: ['justdirethings:time_crystal'],
            text: [
                'Obtaining Time Crystals is a mult-step process across multiple dimensions.',
                ' ',
                Text.of(
                    'To begin, craft a Budding Time Crystal Block and place it in the Overworld; it will slowly charge up and turn a §1Blue§r color. Transfer it to The Nether where it will charge until it turns §6Orange§r, and finally to The End where it will charge until it turns §2Green§r.'
                ),
                ' ',
                'Once fully charged, the Budding Time Crystal Block will begin growing Time Crystal Clusters. Fully grown Clusters may be broken to obtain Time Crystals.',
                ' ',
                'Fully Charged Budding Time Crystal Blocks will slowly decay, at which point they must be transferred back to the Overworld to repeat the cycle.'
            ]
        },
        {
            filter: ['cursedearth:blessed_earth'],
            text: [
                'Rapidly spawns Passive mobs that would otherwise spawn in the area.',
                '',
                'Can spread to adjacent dirt blocks.'
            ]
        },
        {
            filter: ['cursedearth:cursed_earth'],
            text: [
                'Rapidly spawns Hostile mobs that would otherwise spawn in the area.',
                '',
                'Can spread to adjacent dirt blocks. Burns when exposed to daylight.'
            ]
        },
        {
            filter: ['enderio:industrial_insulation_block'],
            text: ['Absorbs and voids any fluids placed nearby.']
        },
        {
            filter: ['naturesaura:vacuum_bottle'],
            text: ['Use a Bottle and Cork in an area devoid of Aura.']
        },
        {
            filter: [Item.of('naturesaura:aura_bottle[naturesaura:aura_bottle_data={aura_type:"naturesaura:nether"}]')],
            text: ['Use a Bottle and Cork in an area of high Aura in the Nether.']
        },
        {
            filter: [
                Item.of('naturesaura:aura_bottle[naturesaura:aura_bottle_data={aura_type:"naturesaura:overworld"}]')
            ],
            text: ['Use a Bottle and Cork in an area of high Aura in the Overworld.']
        },
        {
            filter: [Item.of('naturesaura:aura_bottle[naturesaura:aura_bottle_data={aura_type:"naturesaura:end"}]')],
            text: ['Use a Bottle and Cork in an area of high Aura in the End.']
        }
    ];

    descriptions.forEach((description) => {
        event.add(description.filter, description.text);
    });
});
