[debug]
	# Name: Debug Ingredients
	# Description: Log added and updated ingredients in JEI's ingredient filter.
	# Valid Values: [true, false]
	# Default Value: false
	debugIngredientsEnabled = false

	# Name: Debug GUIs
	# Description: Enable Debug GUIs mode
	# Valid Values: [true, false]
	# Default Value: false
	debugGuis = false

	# Name: Debug Inputs
	# Description: Enable Debug Inputs mode
	# Valid Values: [true, false]
	# Default Value: false
	debugInputs = false

	# Name: Debug Info Tooltips
	# Description: Add debug information to ingredient tooltips when advanced tooltips are enabled.
	# Valid Values: [true, false]
	# Default Value: false
	debugInfoTooltipsEnabled = false

	# Name: Log Search Tree Statistics
	# Description: Log information about the suffix trees used for searching, to help debug JEI.
	# Valid Values: [true, false]
	# Default Value: false
	logSuffixTreeStats = false


