#Base speed of the wheel
# Default: 16
# Range: > 0
wheelBaseSpeed = 16
#Speed of the wheel with a gold block in front
# Default: 24
# Range: > 0
wheelMaxSpeed = 24
#Stress capacity of the wheel
# Default: 16.0
# Range: 0.0 ~ 1.7976931348623157E308
wheelStressCapacity = 16.0
