	#Setting these values to false will disable features using the vanilla isEnabled method
	#It is recommended to create a new world after changing the config!
	["Arts & Crafts Config".Features]
		#Allows flower pots to be dyed when true. Default value: true
		enableDyedFlowerPots = true
		#Should chalk sticks be enabled? Default value: true
		enableChalkSticks = true
		#Allows decorated pots to be dyed when true. Default value: true
		enableDyedDecoratedPots = true
		#When true adds a new creative mode tab full of Arts & Crafts features!
		enableCreativeModeTab = false
		#Allows the player to bleach sheep  (Yirmiri wanted this really bad for some reason)
		bleachableSheep = false

		["Arts & Crafts Config".Features."April Fools Updates"]
			#2025 April fools features
			aprilFools2025 = false
