#List of blocks that are allowed to be covered. Supports '*' as a wildcard.
blocks = ["replication:*_pipe", "oritech:*_pipe*", "oritech:superconductor*", "pipez:*_pipe", "mekanism:*_cable", "mekanism:*_conductor", "mekanism:*_pipe", "mekanism:*_tube", "mekanism:*_transporter", "mekanism_extras:*_cable", "mekanism_extras:*_conductor", "mekanism_extras:*_pipe", "mekanism_extras:*_tube", "mekanism_extras:*_transporter", "thermal:*_duct", "thermal:*_duct_windowed", "computercraft:cable", "powah:energy_cable_*", "pneumaticcraft:*_tube", "ppfluids:fluid_pipe", "prettypipes:pipe", "laserio:laser_*", "cyclic:*_pipe", "embers:*_pipe", "elementalcraft:elementpipe*", "gtceu:*wire", "gtceu:*pipe"]
#List of blocks that are explicitly not allowed to be used as a cover. Supports '*' as a wildcard.
not_allowed_blocks = []
#Whether the facade should be consumed when placed.
consumeFacade = true
#List of blocks that need z-fighting fixes. Supports '*' as a wildcard.
z_fighting = ["ae2:cable_bus"]
